<?php
$q=trim((string)($_GET['historico']??''));$situacao=$_GET['situacao']??'todos';$ini=$_GET['data_ini']??'';$fim=$_GET['data_fim']??'';
$lista=array_values(array_filter($itens,function($i)use($q,$ini,$fim,$situacao){return $i['status']!=='ESTORNADO'&&(!$q||stripos($i['descricao'],$q)!==false)&&(!$ini||$i['data_compra']>=$ini)&&(!$fim||$i['data_compra']<=$fim)&&($situacao==='todos'||($situacao==='conciliados'?!empty($i['cpcontador']):empty($i['cpcontador'])));}));
$itensPorId=array_column($itens,null,'id');
$s=$pdo_master->prepare("SELECT debito_id,credito_id,valor FROM financeiro_cc_estornos WHERE fatura_id=? AND empresa_id=? ORDER BY debito_id");$s->execute([$faturaId,$empresa]);$estornos=$s->fetchAll(PDO::FETCH_ASSOC);
$totalEstornado=array_sum(array_column($estornos,'valor'));
$debitosEstornaveis=array_values(array_filter($itens,static function($i){return $i['natureza']==='D' && $i['status']!=='ESTORNADO' && !$i['cpcontador'];}));
$creditosEstornaveis=array_values(array_filter($itens,static function($i){return $i['natureza']==='C' && $i['status']!=='ESTORNADO' && !$i['cpcontador'];}));
$s=$pdo_master->prepare("SELECT e.id,e.debito_id,e.valor,d.descricao,d.cpcontador,f.competencia,f.status AS status_origem,COALESCE(SUM(a.valor),0) AS aplicado,cp.TIPOES AS cp_tipoes,t.CONTRAP_CBCONTADOR,t.CONTRAP_TIPOES FROM financeiro_cc_creditos_esperados e JOIN financeiro_cc_itens d ON d.id=e.debito_id JOIN financeiro_cc_faturas f ON f.id=d.fatura_id LEFT JOIN financeiro_cc_creditos_aplicados a ON a.esperado_id=e.id LEFT JOIN armazem_cp001 cp ON cp.EMPRESA=e.empresa_id AND cp.CPCONTADOR=d.cpcontador LEFT JOIN armazem_bnc005 t ON t.EMPRESA=cp.EMPRESA AND t.ESCONTADOR=cp.TIPOES WHERE e.empresa_id=? AND e.cartao_id=? GROUP BY e.id,e.debito_id,e.valor,d.descricao,d.cpcontador,f.competencia,f.status,cp.TIPOES,t.CONTRAP_CBCONTADOR,t.CONTRAP_TIPOES ORDER BY f.competencia,d.id");
$s->execute([$empresa,(int)$fatura['cartao_id']]);$creditosEsperados=$s->fetchAll(PDO::FETCH_ASSOC);
$esperadosOrigem=array_values(array_filter($creditosEsperados,static function($e)use($itensPorId){return isset($itensPorId[$e['debito_id']]);}));
$creditosRecebidos=array_values(array_filter($itens,static function($i){return $i['natureza']==='C' && $i['status']!=='ESTORNADO';}));
$s=$pdo_master->prepare("SELECT a.credito_id,a.esperado_id,a.valor,a.mov_credito_39 FROM financeiro_cc_creditos_aplicados a JOIN financeiro_cc_itens i ON i.id=a.credito_id WHERE i.fatura_id=? AND a.empresa_id=?");$s->execute([$faturaId,$empresa]);$aplicadosPorCredito=array_column($s->fetchAll(PDO::FETCH_ASSOC),null,'credito_id');
$s=$pdo_master->prepare("SELECT a.credito_id,a.valor,a.mov_credito_39 FROM financeiro_cc_creditos_avulsos a JOIN financeiro_cc_itens i ON i.id=a.credito_id WHERE i.fatura_id=? AND a.empresa_id=?");$s->execute([$faturaId,$empresa]);$avulsosPorCredito=array_column($s->fetchAll(PDO::FETCH_ASSOC),null,'credito_id');
$creditosSemClassificacao=array_values(array_filter($creditosRecebidos,static function($c)use($aplicadosPorCredito,$avulsosPorCredito){return !isset($aplicadosPorCredito[$c['id']]) && !isset($avulsosPorCredito[$c['id']]);}));
$creditosEstornaveis=array_values(array_filter($creditosEstornaveis,static function($c)use($aplicadosPorCredito,$avulsosPorCredito){return !isset($aplicadosPorCredito[$c['id']]) && !isset($avulsosPorCredito[$c['id']]);}));
$debitosEstornaveis=array_values(array_filter($debitosEstornaveis,static function($d)use($creditosEsperados){return !in_array((int)$d['id'],array_map('intval',array_column($creditosEsperados,'debito_id')),true);}));
$paresEstornaveis=[];
foreach($creditosEstornaveis as $credito){
    $debitosMesmoValor=array_values(array_filter($debitosEstornaveis,static function($debito)use($credito){return (int)round((float)$debito['valor']*100)===(int)round((float)$credito['valor']*100);}));
    if($debitosMesmoValor)$paresEstornaveis[]=['credito'=>$credito,'debitos'=>$debitosMesmoValor];
}
$idsCreditosEstornaveis=array_fill_keys(array_map(static function($par){return (int)$par['credito']['id'];},$paresEstornaveis),true);
$creditosParaClassificar=array_values(array_filter($creditosRecebidos,static function($credito)use($idsCreditosEstornaveis){return !isset($idsCreditosEstornaveis[(int)$credito['id']]);}));
$pendentesParaClassificar=array_values(array_filter($creditosSemClassificacao,static function($credito)use($idsCreditosEstornaveis){return !isset($idsCreditosEstornaveis[(int)$credito['id']]);}));
$candidatosCredito=array_values(array_filter($creditosEsperados,static function($e)use($fatura){return $e['status_origem']==='ENCERRADA' && $e['competencia']<$fatura['competencia'] && (int)round(((float)$e['valor']-(float)$e['aplicado'])*100)>0;}));
$chaveEstorno=static function(string $descricao):string{return preg_replace('/^(EST|REV|AJUSTE CR)\s+/','',normalizarDescricaoCartao($descricao));};
$sugestoesOrigem=[];
if($creditosRecebidos){
    $valores=array_values(array_unique(array_map(static function($c){return number_format((float)$c['valor'],2,'.','');},$creditosRecebidos)));
    $marcadores=implode(',',array_fill(0,count($valores),'?'));
    $s=$pdo_master->prepare("SELECT d.id,d.descricao,d.valor,f.id AS fatura_id,f.competencia,f.status FROM financeiro_cc_itens d JOIN financeiro_cc_faturas f ON f.id=d.fatura_id AND f.empresa_id=d.empresa_id WHERE f.empresa_id=? AND f.cartao_id=? AND f.competencia<? AND d.natureza='D' AND d.status<>'ESTORNADO' AND d.cpcontador IS NOT NULL AND d.valor IN ($marcadores) ORDER BY f.competencia DESC,d.id DESC");
    $s->execute(array_merge([$empresa,(int)$fatura['cartao_id'],$fatura['competencia']],$valores));
    foreach($s as $origem){$chave=number_format((float)$origem['valor'],2,'.','').'|'.$chaveEstorno((string)$origem['descricao']);if(count($sugestoesOrigem[$chave]??[])<3)$sugestoesOrigem[$chave][]=$origem;}
}
$vinculados=array_values(array_filter($lista,static function($i){return $i['natureza']==='D'&&!empty($i['cpcontador']);}));
$sqlCp="SELECT cp.CPCONTADOR,cp.DTCOMPRA,cp.DTVENC,cp.TITULO,COALESCE(NULLIF(cp.VLRRESTANTE,0),cp.VLRPARCELA,cp.VALORCOMPRA) valor,COALESCE(NULLIF(f.APELIDO,''),f.NOME) fornecedor FROM armazem_cp001 cp LEFT JOIN armazem_cp003 f ON f.EMPRESA=cp.EMPRESA AND f.FCONTADOR=cp.FCONTADOR WHERE cp.EMPRESA=? AND cp.STATUS<>'QT' AND cp.DTPAGTO IS NULL AND COALESCE(cp.VLRPAGO,0)=0 AND COALESCE(cp.excluido_firebird,'N')<>'S' AND NOT EXISTS(SELECT 1 FROM financeiro_cc_itens x WHERE x.empresa_id=cp.EMPRESA AND x.cpcontador=cp.CPCONTADOR)";$parCp=[$empresa];if($ini){$sqlCp.=" AND DATE(cp.DTCOMPRA)>=?";$parCp[]=$ini;}if($fim){$sqlCp.=" AND DATE(cp.DTCOMPRA)<=?";$parCp[]=$fim;}if($q){$sqlCp.=" AND (cp.TITULO LIKE ? OR f.NOME LIKE ? OR f.APELIDO LIKE ?)";$busca='%'.$q.'%';array_push($parCp,$busca,$busca,$busca);}$sqlCp.=" ORDER BY cp.DTCOMPRA DESC,cp.CPCONTADOR DESC";$stmtCp=$pdo_master->prepare($sqlCp);$stmtCp->execute($parCp);$cpSistema=$stmtCp->fetchAll(PDO::FETCH_ASSOC);
$seguros=[];$manual=[];$sem=[];$contagens=cccContarValoresPendentes($lista);
foreach($lista as $i){
    if($i['natureza']!=='D'||$i['cpcontador'])continue;
    $c=cccCandidatos($pdo_master,$i,$fatura['vencimento']);
    $automatico=cccCandidatoAutomatico($i,$c,$contagens,$fatura['vencimento']);
    if($automatico)$seguros[]=[$i,$automatico];
    elseif($c)$manual[]=[$i,$c];
    else $sem[]=$i;
}
function ccForm(int $fid,int $iid,int $cp):string{return '<form method="post"><input type="hidden" name="acao" value="vincular"><input type="hidden" name="fatura_id" value="'.$fid.'"><input type="hidden" name="item_id" value="'.$iid.'"><input type="hidden" name="cpcontador" value="'.$cp.'"><button class="btn btn-sm btn-primary">Conciliar</button></form>';}
function ccParcelaExtrato(array $item):string
{
    $tipo=(string)($item['tipo_lancamento']??'');
    return preg_match('/(\d+)\s*\/\s*(\d+)/',$tipo,$m)?$m[1].'/'.$m[2]:'-';
}
require '../../layout/header.php';?>
<style>
.fatura-cartao-quadro,.sistema-cp-quadro{overflow-x:visible}
.conciliacao-fontes>form{display:none}
.fatura-cartao-quadro table,.sistema-cp-quadro table{table-layout:fixed;width:100%;font-size:12px}
.fatura-cartao-quadro th,.fatura-cartao-quadro td,.sistema-cp-quadro th,.sistema-cp-quadro td{white-space:normal;overflow-wrap:break-word;vertical-align:middle}
.fatura-cartao-quadro th:nth-child(1),.fatura-cartao-quadro td:nth-child(1){width:40px;text-align:center}
.fatura-cartao-quadro th:nth-child(2),.fatura-cartao-quadro td:nth-child(2){width:78px}
.fatura-cartao-quadro th:nth-child(4),.fatura-cartao-quadro td:nth-child(4){width:56px;text-align:center;white-space:nowrap}
.fatura-cartao-quadro th:nth-child(5),.fatura-cartao-quadro td:nth-child(5){width:88px;white-space:nowrap}
.fatura-cartao-quadro th:nth-child(6),.fatura-cartao-quadro td:nth-child(6){width:82px}
.sistema-cp-quadro th:nth-child(1),.sistema-cp-quadro td:nth-child(1){width:38px}
.sistema-cp-quadro th:nth-child(2),.sistema-cp-quadro td:nth-child(2){width:30%}
.sistema-cp-quadro th:nth-child(3),.sistema-cp-quadro td:nth-child(3),.sistema-cp-quadro th:nth-child(4),.sistema-cp-quadro td:nth-child(4){width:60px}
.sistema-cp-quadro th:nth-child(5),.sistema-cp-quadro td:nth-child(5){width:auto}
.sistema-cp-quadro th:nth-child(6),.sistema-cp-quadro td:nth-child(6){width:72px;white-space:nowrap}
@media(max-width:768px){.fatura-cartao-quadro,.sistema-cp-quadro{overflow-x:auto}}
@media(min-width:992px){.conciliacao-fontes>.col-xl-7,.conciliacao-fontes>.col-xl-5{flex:0 0 auto;width:50%}}
</style>
<section class="card mb-3"><div class="card-body d-flex justify-content-between align-items-center"><div><span class="badge text-bg-primary mb-2">Financeiro</span><h1 class="h4 mb-1">Conciliacao de Cartao de Credito</h1><p class="text-muted mb-0">Compare a fatura com os lancamentos do sistema antes de conciliar.</p></div><a href="conciliacao_cartao_credito.php" class="btn btn-outline-secondary">Voltar</a></div></section>
<?php if($msg):?><div class="alert alert-success"><?=htmlspecialchars($msg)?></div><?php endif;?><?php if($erro):?><div class="alert alert-danger"><?=htmlspecialchars($erro)?></div><?php endif;?>
<section class="card mb-3"><div class="card-body"><form class="row g-2 align-items-end"><input type="hidden" name="fatura_id" value="<?=$faturaId?>"><div class="col-md-2"><label class="form-label">Data inicial</label><input type="date" name="data_ini" value="<?=htmlspecialchars($ini)?>" class="form-control"></div><div class="col-md-2"><label class="form-label">Data final</label><input type="date" name="data_fim" value="<?=htmlspecialchars($fim)?>" class="form-control"></div><div class="col-md-4"><label class="form-label">Historico</label><input name="historico" value="<?=htmlspecialchars($q)?>" placeholder="Buscar no historico" class="form-control"></div><div class="col-md-2"><label class="form-label">Situacao</label><select name="situacao" class="form-select"><option value="pendentes" <?=$situacao==='pendentes'?'selected':''?>>Nao conciliados</option><option value="conciliados" <?=$situacao==='conciliados'?'selected':''?>>Conciliados</option><option value="todos" <?=$situacao==='todos'?'selected':''?>>Todos</option></select></div><div class="col-md-2"><button class="btn btn-primary w-100">Filtrar</button></div></form></div></section>
<div class="row g-3 mb-3"><div class="col-md-4"><div class="border p-3"><small class="text-muted">Fatura filtrada</small><div class="h4"><?=moedaCartaoCredito(array_sum(array_map(function($i){return $i['natureza']==='D'?(float)$i['valor']:($i['natureza']==='C'?-(float)$i['valor']:0);},$lista)))?></div><small><?=count($lista)?> lancamento(s)</small></div></div><div class="col-md-4"><div class="border p-3"><small class="text-muted">Sistema CP001 filtrado</small><div class="h4"><?=moedaCartaoCredito(array_sum(array_column($cpSistema,'valor')))?></div><small><?=count($cpSistema)?> lancamento(s)</small></div></div><div class="col-md-4"><div class="border p-3"><small class="text-muted">Sugestoes automaticas seguras</small><div class="h4"><?=count($seguros)?></div><small><?=count($manual)?> para escolha manual</small></div></div></div>
<section class="card mb-3"><div class="card-header d-flex justify-content-between align-items-center"><h2 class="h6 mb-0">Baixa dos CPs da fatura</h2><span class="badge text-bg-light border"><?=htmlspecialchars($fatura['status'])?></span></div><div class="card-body">
<?php if($fatura['status']==='IMPORTADA'):?>
<div class="row g-2 mb-3"><div class="col-md-3">Compras a baixar: <strong><?=moedaCartaoCredito((float)$fatura['total_debitos']-$totalEstornado)?></strong></div><div class="col-md-3">Valor liquido da fatura: <strong><?=moedaCartaoCredito($fatura['total_fatura'])?></strong></div><div class="col-md-3">Creditos a classificar: <strong><?=moedaCartaoCredito(array_sum(array_column($creditosSemClassificacao,'valor')))?></strong></div><div class="col-md-3">Compras sem CP: <strong><?=$pendentesFechamento?></strong></div></div>
<?php if($creditosSemClassificacao):?><div class="alert alert-warning mb-3">Classifique os <?=count($creditosSemClassificacao)?> credito(s) pendente(s) antes de baixar os CPs.</div><?php endif;?>
<?php if($bloqueioPagamento):?><div class="alert alert-warning mb-3"><?=htmlspecialchars($bloqueioPagamento)?></div><?php endif;?>
<form method="post" class="row g-2 align-items-end" onsubmit="return confirm('Confirmar baixa de todos os CPs na conta 39? Os pagamentos bancarios nao serao lancados automaticamente.');"><input type="hidden" name="acao" value="baixar_cps_fatura"><input type="hidden" name="fatura_id" value="<?=$faturaId?>"><input type="hidden" name="token" value="<?=htmlspecialchars($_SESSION['cc_fechamento_token'])?>"><div class="col-md-4"><label class="form-label">Data da baixa dos CPs</label><input class="form-control" type="date" name="data_baixa" value="<?=date('Y-m-d')?>" required></div><div class="col-md-4"><button class="btn btn-primary w-100" <?=$pendentesFechamento||$creditosSemClassificacao||$bloqueioPagamento?'disabled':''?>>Baixar CPs na conta 39</button></div></form>
<?php elseif($fatura['status']==='ENCERRADA' && !$fechamento):?><div>Fatura fechada e lancada. Todos os CPs foram baixados na conta 39. Os pagamentos por debito bancario ou boleto devem ser conciliados nessa conta.</div>
<?php elseif($fatura['status']==='AJUSTE_PENDENTE' && $fechamento):?>
<p class="mb-3">Pagamento de <?=moedaCartaoCredito($fechamento['total_pagamento'])?> registrado. A devolucao de <?=moedaCartaoCredito($fechamento['total_ajuste'])?> ainda precisa ser creditada na conta 39.</p><form method="post" class="row g-2 align-items-end" onsubmit="return confirm('Registrar o credito da devolucao na conta 39?');"><input type="hidden" name="acao" value="ajustar_credito"><input type="hidden" name="fatura_id" value="<?=$faturaId?>"><input type="hidden" name="token" value="<?=htmlspecialchars($_SESSION['cc_fechamento_token'])?>"><div class="col-md-8"><label class="form-label">TIPOES do credito da devolucao</label><select name="tipoes_ajuste" class="form-select" required><option value="">Selecione</option><?php foreach($tiposAjuste as $tipo):?><option value="<?=(int)$tipo['ESCONTADOR']?>"><?=htmlspecialchars($tipo['DESCES'].' ('.$tipo['ESCONTADOR'].')')?></option><?php endforeach;?></select></div><div class="col-md-4"><button class="btn btn-primary w-100">Registrar ajuste e encerrar</button></div></form>
<?php elseif($fechamento):?><div>Fatura encerrada. Pagamento de <?=moedaCartaoCredito($fechamento['total_pagamento'])?> pela conta <?=(int)$fechamento['conta_pagamento']?> em <?=dataCartaoCredito($fechamento['data_pagamento'])?>.</div><?php endif;?>
</div></section>
<section class="card mb-3"><div class="card-header d-flex justify-content-between align-items-center"><h2 class="h6 mb-0">Itens estornados na fatura</h2><span class="badge text-bg-secondary"><?=count($estornos)?> par(es)</span></div>
<?php if($fatura['status']==='IMPORTADA'):?><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead class="table-primary"><tr><th>Credito da fatura</th><th class="text-end">Valor</th><th>Debito de mesmo valor nesta fatura</th><th class="text-end">Acao</th></tr></thead><tbody><?php foreach($paresEstornaveis as $par):$credito=$par['credito'];$formId='estorno-'.$credito['id'];?><tr><td>#<?=(int)$credito['id']?> | <?=htmlspecialchars($credito['descricao'])?></td><td class="text-end"><?=moedaCartaoCredito($credito['valor'])?></td><td><select class="form-select form-select-sm" form="<?=$formId?>" name="debito_id" required><option value="">Selecione o debito</option><?php foreach($par['debitos'] as $debito):?><option value="<?=(int)$debito['id']?>">#<?=(int)$debito['id']?> | <?=htmlspecialchars($debito['descricao'])?></option><?php endforeach;?></select></td><td class="text-end"><form method="post" id="<?=$formId?>" onsubmit="return confirm('Confirmar a anulacao destes dois itens na mesma fatura?');"><input type="hidden" name="acao" value="marcar_estorno"><input type="hidden" name="fatura_id" value="<?=$faturaId?>"><input type="hidden" name="credito_id" value="<?=(int)$credito['id']?>"><input type="hidden" name="token" value="<?=htmlspecialchars($_SESSION['cc_fechamento_token'])?>"><button class="btn btn-sm btn-outline-primary">Confirmar par</button></form></td></tr><?php endforeach;?><?php if(!$paresEstornaveis):?><tr><td colspan="4" class="text-center text-muted py-3">Nenhum debito e credito livres de mesmo valor nesta fatura.</td></tr><?php endif;?></tbody></table></div><?php endif;?>
<div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead class="table-primary"><tr><th>Debito</th><th>Credito</th><th class="text-end">Valor de cada item</th><th class="text-end">Saldo</th></tr></thead><tbody><?php foreach($estornos as $par):$d=$itensPorId[$par['debito_id']]??null;$c=$itensPorId[$par['credito_id']]??null;?><tr><td>#<?=(int)$par['debito_id']?> | <?=htmlspecialchars($d['descricao']??'-')?></td><td>#<?=(int)$par['credito_id']?> | <?=htmlspecialchars($c['descricao']??'-')?></td><td class="text-end"><?=moedaCartaoCredito($par['valor'])?></td><td class="text-end">R$ 0,00</td></tr><?php endforeach;?><?php if(!$estornos):?><tr><td colspan="4" class="text-center text-muted py-3">Nenhum estorno confirmado nesta fatura.</td></tr><?php endif;?></tbody></table></div></section>
<section class="card mb-3"><div class="card-header"><h2 class="h6 mb-0">Creditos de faturas seguintes</h2></div>
<?php $debitosElegiveis=array_values(array_filter($itens,static function($i)use($esperadosOrigem){return $i['natureza']==='D' && $i['status']!=='ESTORNADO' && $i['cpcontador'] && !in_array((int)$i['id'],array_map('intval',array_column($esperadosOrigem,'debito_id')),true);}));?>
<?php if($debitosElegiveis):?><div class="card-body border-bottom"><form method="post" class="row g-2 align-items-end"><input type="hidden" name="acao" value="marcar_credito_esperado"><input type="hidden" name="fatura_id" value="<?=$faturaId?>"><input type="hidden" name="token" value="<?=htmlspecialchars($_SESSION['cc_fechamento_token'])?>"><div class="col-md-9"><label class="form-label">Compra a estornar em fatura futura</label><select class="form-select" name="debito_id" required><option value="">Selecione</option><?php foreach($debitosElegiveis as $i):?><option value="<?=(int)$i['id']?>">#<?=(int)$i['id']?> | <?=htmlspecialchars($i['descricao'])?> | <?=moedaCartaoCredito($i['valor'])?></option><?php endforeach;?></select></div><div class="col-md-3"><button class="btn btn-outline-primary w-100">Aguardar estorno</button></div></form></div><?php endif;?>
<div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead class="table-primary"><tr><th>Compra original</th><th>CP</th><th class="text-end">Valor esperado</th><th class="text-end">Recebido</th><th class="text-end">Pendente</th><th class="text-end">Acao</th></tr></thead><tbody><?php foreach($esperadosOrigem as $e):?><tr><td>#<?=(int)$e['debito_id']?> | <?=htmlspecialchars($e['descricao'])?></td><td><?=(int)$e['cpcontador']?></td><td class="text-end"><?=moedaCartaoCredito($e['valor'])?></td><td class="text-end"><?=moedaCartaoCredito($e['aplicado'])?></td><td class="text-end"><?=moedaCartaoCredito(max(0,(float)$e['valor']-(float)$e['aplicado']))?></td><td class="text-end"><?php if((float)$e['aplicado']<=0):?><form method="post" onsubmit="return confirm('Cancelar a espera pelo credito da compra #<?=(int)$e['debito_id']?>?');"><input type="hidden" name="acao" value="cancelar_credito_esperado"><input type="hidden" name="fatura_id" value="<?=$faturaId?>"><input type="hidden" name="esperado_id" value="<?=(int)$e['id']?>"><input type="hidden" name="token" value="<?=htmlspecialchars($_SESSION['cc_fechamento_token'])?>"><button class="btn btn-sm btn-outline-secondary">Cancelar espera</button></form><?php else:?>-<?php endif;?></td></tr><?php endforeach;?><?php if(!$esperadosOrigem):?><tr><td colspan="6" class="text-center text-muted py-3">Nenhum credito esperado nesta fatura.</td></tr><?php endif;?></tbody></table></div></section>
<?php if($creditosParaClassificar):?><section class="card mb-3"><div class="card-header d-flex justify-content-between"><h2 class="h6 mb-0">Outros creditos recebidos nesta fatura</h2><span class="badge text-bg-light border"><?=count($pendentesParaClassificar)?> pendente(s)</span></div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead class="table-primary"><tr><th>Credito</th><th class="text-end">Valor</th><th>Situacao</th><th>Acao</th></tr></thead><tbody>
<?php foreach($creditosParaClassificar as $c):
    $v=$aplicadosPorCredito[$c['id']]??null;
    $avulso=$avulsosPorCredito[$c['id']]??null;
    $opcoes=array_values(array_filter($candidatosCredito,static function($e)use($c){return (int)round(((float)$e['valor']-(float)$e['aplicado'])*100)>=(int)round((float)$c['valor']*100);}));
?><tr><td>#<?=(int)$c['id']?> | <?=htmlspecialchars($c['descricao'])?></td><td class="text-end"><?=moedaCartaoCredito($c['valor'])?></td><td><?=($v?'Estorno de compra anterior':($avulso?'Credito avulso':'Pendente'))?></td><td>
<?php if(!$v && !$avulso && $fatura['status']==='IMPORTADA'):?><details class="cc-credit-actions"><summary class="btn btn-sm btn-outline-primary">Classificar</summary><div class="d-flex flex-wrap gap-3 py-2">
<?php if($opcoes):?><form method="post" class="d-flex flex-wrap gap-2 align-items-end" onsubmit="return confirm('Vincular este credito a compra anterior e lancar na conta 39?');"><input type="hidden" name="acao" value="aplicar_credito_posterior"><input type="hidden" name="fatura_id" value="<?=$faturaId?>"><input type="hidden" name="credito_id" value="<?=(int)$c['id']?>"><input type="hidden" name="token" value="<?=htmlspecialchars($_SESSION['cc_fechamento_token'])?>"><div><label class="form-label small">Compra anterior</label><select name="esperado_id" class="form-select form-select-sm" required><option value="">Selecione</option><?php foreach($opcoes as $e):?><option value="<?=(int)$e['id']?>">#<?=(int)$e['debito_id']?> | <?=htmlspecialchars($e['competencia'].' - '.$e['descricao'])?> | <?=moedaCartaoCredito((float)$e['valor']-(float)$e['aplicado'])?></option><?php endforeach;?></select></div><div><label class="form-label small">TIPOES do credito</label><select name="tipoes_credito" class="form-select form-select-sm" required><option value="">Selecione</option><?php foreach($tiposAjuste as $tipo):?><option value="<?=(int)$tipo['ESCONTADOR']?>"><?=htmlspecialchars($tipo['DESCES'].' ('.$tipo['ESCONTADOR'].')')?></option><?php endforeach;?></select></div><div><label class="form-label small">Reversao de investimento</label><select name="tipoes_reversao" class="form-select form-select-sm"><option value="">Nao se aplica</option><?php foreach($tiposReversao as $tipo):?><option value="<?=(int)$tipo['ESCONTADOR']?>"><?=htmlspecialchars($tipo['DESCES'].' ('.$tipo['ESCONTADOR'].')')?></option><?php endforeach;?></select></div><button class="btn btn-sm btn-outline-primary">Vincular estorno</button></form><?php else:?>
<div class="small text-muted align-self-center"><?php $chave=number_format((float)$c['valor'],2,'.','').'|'.$chaveEstorno((string)$c['descricao']);$esperaEncontrada=false;foreach($sugestoesOrigem[$chave]??[] as $origem):$espera=array_values(array_filter($creditosEsperados,static function($e)use($origem){return (int)$e['debito_id']===(int)$origem['id'];}));if($espera && $origem['status']!=='ENCERRADA'):$esperaEncontrada=true;?>Credito esperado da compra <a href="?fatura_id=<?=(int)$origem['fatura_id']?>">#<?=(int)$origem['id']?> (<?=$origem['competencia']?>)</a> ja cadastrado. Encerre a fatura de origem para vincular este credito.<?php endif;endforeach;if(!$esperaEncontrada):?>Sem compra anterior fechada aguardando este credito.<?php foreach($sugestoesOrigem[$chave]??[] as $origem):?> <a href="?fatura_id=<?=(int)$origem['fatura_id']?>">Possivel compra #<?=(int)$origem['id']?> (<?=$origem['competencia']?>)</a><?php if($origem['status']!=='ENCERRADA'):?> - fatura ainda aberta.<?php endif;?><?php endforeach;endif;?></div>
<?php endif;?>
<form method="post" class="d-flex flex-wrap gap-2 align-items-end" onsubmit="return confirm('Classificar este item como credito avulso e lancar na conta 39?');"><input type="hidden" name="acao" value="aplicar_credito_avulso"><input type="hidden" name="fatura_id" value="<?=$faturaId?>"><input type="hidden" name="credito_id" value="<?=(int)$c['id']?>"><input type="hidden" name="token" value="<?=htmlspecialchars($_SESSION['cc_fechamento_token'])?>"><div><label class="form-label small">TIPOES do credito avulso</label><select name="tipoes_credito" class="form-select form-select-sm" required><option value="">Selecione</option><?php foreach($tiposAjuste as $tipo):?><option value="<?=(int)$tipo['ESCONTADOR']?>"><?=htmlspecialchars($tipo['DESCES'].' ('.$tipo['ESCONTADOR'].')')?></option><?php endforeach;?></select></div><button class="btn btn-sm btn-outline-success">Classificar avulso</button></form></div></details>
<?php elseif($v || $avulso):?><span class="small text-muted">Conta 39: movimento <?=(int)($v['mov_credito_39']??$avulso['mov_credito_39'])?></span><?php if($fatura['status']==='IMPORTADA'):?><form method="post" class="d-inline ms-2" onsubmit="return confirm('Desfazer a classificacao e cancelar os movimentos ainda nao conciliados?');"><input type="hidden" name="acao" value="desfazer_credito"><input type="hidden" name="fatura_id" value="<?=$faturaId?>"><input type="hidden" name="credito_id" value="<?=(int)$c['id']?>"><input type="hidden" name="token" value="<?=htmlspecialchars($_SESSION['cc_fechamento_token'])?>"><button class="btn btn-sm btn-outline-secondary">Reclassificar</button></form><?php endif;?><?php else:?>Fatura encerrada<?php endif;?></td></tr><?php endforeach;?>
</tbody></table></div></section><?php endif;?>
<?php if($vinculados):?><section class="card mb-3"><div class="card-header d-flex justify-content-between align-items-center"><h2 class="h6 mb-0">Itens conciliados com CP</h2><span class="badge text-bg-success"><?=count($vinculados)?></span></div><div class="table-responsive" style="max-height:400px"><table class="table table-sm table-hover align-middle mb-0"><thead class="table-primary"><tr><th>Fatura</th><th>Data</th><th>Historico</th><th>CP</th><th class="text-end">Valor</th><th>Acao</th></tr></thead><tbody><?php foreach($vinculados as $i):?><tr><td>#<?=(int)$i['id']?></td><td><?=dataCartaoCredito($i['data_compra'])?></td><td><?=htmlspecialchars($i['descricao'])?></td><td><?=(int)$i['cpcontador']?></td><td class="text-end"><?=moedaCartaoCredito($i['valor'])?></td><td><?php if($fatura['status']==='IMPORTADA'):?><form method="post" onsubmit="return confirm('Desfazer o match? Se o CP foi criado nesta rotina, ele sera cancelado apos conferir os vinculos.');"><input type="hidden" name="acao" value="desfazer_match"><input type="hidden" name="fatura_id" value="<?=$faturaId?>"><input type="hidden" name="item_id" value="<?=(int)$i['id']?>"><input type="hidden" name="token" value="<?=htmlspecialchars($_SESSION['cc_fechamento_token'])?>"><button class="btn btn-sm btn-outline-danger">Desfazer</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>
<?php if($fatura['status']==='IMPORTADA'):?>
<?php function ccTabela(array $grupos,string $titulo,string $texto,int $fid,string $cor='primary'):void{$form='lote-'.md5($titulo);?><section class="card mb-3"><div class="card-header d-flex justify-content-between align-items-center"><div><h2 class="h6 mb-1"><?=$titulo?></h2><small class="text-muted"><?=$texto?></small></div><button form="<?=$form?>" class="btn btn-sm btn-<?=$cor?>" <?=$grupos?'':'disabled'?>>Conciliar <?=count($grupos)?> selecionado(s)</button></div><form method="post" id="<?=$form?>"><input type="hidden" name="acao" value="vincular_lote"><input type="hidden" name="fatura_id" value="<?=$fid?>"><?php foreach($grupos as $m):?><input type="hidden" name="matches[<?=$m[0]['id']?>]" value="<?=$m[1]['CPCONTADOR']?>"><?php endforeach;?></form><div class="table-responsive"><table class="table table-sm table-hover align-middle mb-0"><thead class="table-<?=$cor?>"><tr><th>Fatura</th><th>Data fatura</th><th>Historico fatura</th><th>Sistema</th><th>Vencimento</th><th class="text-end">Valor</th><th>Acao</th></tr></thead><tbody><?php foreach($grupos as $m):?><tr><td>#<?=$m[0]['id']?></td><td><?=dataCartaoCredito($m[0]['data_compra'])?></td><td><?=htmlspecialchars($m[0]['descricao'])?></td><td>CP <?=$m[1]['CPCONTADOR']?> | <?=htmlspecialchars($m[1]['fornecedor'].' | '.$m[1]['TITULO'])?></td><td><?=dataCartaoCredito($m[1]['DTVENC'])?></td><td class="text-end"><?=moedaCartaoCredito($m[0]['valor'])?></td><td><?=ccForm($fid,$m[0]['id'],$m[1]['CPCONTADOR'])?></td></tr><?php endforeach;?><?php if(!$grupos):?><tr><td colspan="7" class="text-center text-muted py-3">Nenhum match para os filtros atuais.</td></tr><?php endif;?></tbody></table></div></section><?php }?>
<?php ccTabela($seguros,'Matches seguros automaticos','Data, valor e historico identificam uma unica correspondencia.',$faturaId);?>
<section class="card mb-3">
    <div class="card-header d-flex justify-content-between align-items-center">
        <div><h2 class="h6 mb-1">Conferencia manual guiada</h2><small class="text-muted">Escolha o CP correto em cada linha e concilie varios de uma vez.</small></div>
        <button form="manual-lote" class="btn btn-sm btn-primary" <?=$manual?'':'disabled'?>>Conciliar selecionados</button>
    </div>
    <form method="post" id="manual-lote"><input type="hidden" name="acao" value="vincular_lote"><input type="hidden" name="fatura_id" value="<?=$faturaId?>"></form>
    <div class="table-responsive"><table class="table table-sm table-hover align-middle mb-0"><thead class="table-primary"><tr><th>Fatura</th><th>Data</th><th>Historico</th><th class="text-end">Valor</th><th style="min-width:360px">Escolher lancamento do sistema</th></tr></thead><tbody>
    <?php foreach($manual as $m):?><tr><td>#<?=$m[0]['id']?></td><td><?=dataCartaoCredito($m[0]['data_compra'])?></td><td><?=htmlspecialchars($m[0]['descricao'])?></td><td class="text-end"><?=moedaCartaoCredito($m[0]['valor'])?></td><td><select form="manual-lote" name="matches[<?=$m[0]['id']?>]" class="form-select form-select-sm cc-manual-match"><option value="">Nao conciliar agora</option><?php foreach($m[1] as $cp):?><option value="<?=$cp['CPCONTADOR']?>">CP <?=$cp['CPCONTADOR']?> | <?=dataCartaoCredito($cp['DTVENC'])?> | <?=htmlspecialchars($cp['fornecedor'].' | '.$cp['TITULO'])?></option><?php endforeach;?></select></td></tr><?php endforeach;?>
    <?php if(!$manual):?><tr><td colspan="5" class="text-center text-muted py-3">Nenhum match manual para os filtros atuais.</td></tr><?php endif;?></tbody></table></div>
</section>
<div class="row g-3 align-items-start conciliacao-fontes">
<div class="col-xl-7"><section class="card h-100"><div class="card-header d-flex flex-wrap justify-content-between gap-2"><div><h2 class="h6 mb-1">Extrato da fatura nao conciliado</h2><div class="text-muted small">Use os filtros para consultar pendentes, conciliados ou todos os lancamentos.</div><div class="mt-2 d-flex flex-wrap gap-2"><span class="badge text-bg-light border"><?=count($sem)?> lancamento(s)</span><span class="badge text-bg-primary">Total: <?=moedaCartaoCredito(array_sum(array_column($sem,'valor')))?></span></div></div><div class="d-flex flex-wrap align-items-end gap-2"><div><label class="form-label small mb-1" for="tipoes-gerar-cp">TIPOES dos CPs</label><select form="gerar" id="tipoes-gerar-cp" name="tipoes" class="form-select form-select-sm" required><option value="">Selecione</option><?php foreach($tiposCp as $tipo):?><option value="<?=(int)$tipo['ESCONTADOR']?>"><?=htmlspecialchars($tipo['DESCES'].' ('.$tipo['ESCONTADOR'].')')?></option><?php endforeach;?></select></div><button type="button" class="btn btn-sm btn-outline-secondary" onclick="document.querySelectorAll('.cc-sem').forEach(x=>x.checked=true)">Selecionar todos</button><button form="gerar" class="btn btn-sm btn-primary" <?=$tiposCp?'':'disabled'?>>Gerar CP selecionados</button></div></div><div class="table-responsive fatura-cartao-quadro"><table class="table table-sm table-hover align-middle mb-0"><thead class="table-primary"><tr><th>Sel.</th><th>Data</th><th>Historico</th><th>Parcela</th><th class="text-end">Valor</th><th>Status</th></tr></thead><tbody><?php foreach($sem as $i):?><tr><td><input form="gerar" class="cc-sem" type="checkbox" name="itens[]" value="<?=$i['id']?>"></td><td><?=dataCartaoCredito($i['data_compra'])?></td><td><?=htmlspecialchars($i['descricao'])?></td><td><?=htmlspecialchars(ccParcelaExtrato($i))?></td><td class="text-end"><?=moedaCartaoCredito($i['valor'])?></td><td><span class="badge text-bg-warning">Pendente</span></td></tr><?php endforeach;?><?php if(!$sem):?><tr><td colspan="6" class="text-center text-muted py-3">Nenhum item pendente na fatura.</td></tr><?php endif;?></tbody></table></div></section></div><form method="post" id="gerar"><input type="hidden" name="acao" value="gerar"><input type="hidden" name="fatura_id" value="<?=$faturaId?>"></form>
<div class="col-xl-5"><section class="card h-100"><div class="card-header"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2"><h2 class="h6 mb-0">Sistema CP001 nao conciliado</h2><div class="d-flex flex-wrap gap-2"><span class="badge text-bg-light border"><?=count($cpSistema)?> lancamento(s)</span><span class="badge text-bg-primary">Total: <?=moedaCartaoCredito(array_sum(array_column($cpSistema,'valor')))?></span></div></div></div><div class="table-responsive sistema-cp-quadro"><table class="table table-sm table-hover align-middle mb-0"><thead class="table-primary"><tr><th>CP</th><th>Fornecedor</th><th>Compra</th><th>Vencimento</th><th>Historico</th><th class="text-end">Valor</th></tr></thead><tbody><?php foreach($cpSistema as $cp):?><tr><td><?=$cp['CPCONTADOR']?></td><td><?=htmlspecialchars($cp['fornecedor']?:'-')?></td><td><?=dataCartaoCredito($cp['DTCOMPRA'])?></td><td><?=dataCartaoCredito($cp['DTVENC'])?></td><td><?=htmlspecialchars($cp['TITULO']?:'-')?></td><td class="text-end"><?=moedaCartaoCredito($cp['valor'])?></td></tr><?php endforeach;?><?php if(!$cpSistema):?><tr><td colspan="6" class="text-center text-muted py-3">Nenhum CP do sistema para os filtros atuais.</td></tr><?php endif;?></tbody></table></div></section></div>
</div>
<?php else:?>
<section class="card mb-3"><div class="card-header fw-semibold">Lancamentos da fatura</div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead class="table-primary"><tr><th>Data</th><th>Historico</th><th>Natureza</th><th>Situacao</th><th>CP</th><th class="text-end">Valor</th></tr></thead><tbody><?php foreach($itens as $i):?><tr><td><?=dataCartaoCredito($i['data_compra'])?></td><td><?=htmlspecialchars($i['descricao'])?></td><td><?=htmlspecialchars($i['natureza'])?></td><td><?=htmlspecialchars($i['status'])?></td><td><?=$i['cpcontador']?(int)$i['cpcontador']:'-'?></td><td class="text-end"><?=moedaCartaoCredito($i['valor'])?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php endif;?>
<script>
document.querySelectorAll('.cc-manual-match').forEach(select => {
    select.addEventListener('change', () => {
        const escolhidos = new Set([...document.querySelectorAll('.cc-manual-match')].map(item => item.value).filter(Boolean));
        document.querySelectorAll('.cc-manual-match').forEach(item => {
            [...item.options].forEach(option => {
                option.disabled = option.value !== '' && option.value !== item.value && escolhidos.has(option.value);
                option.hidden = option.disabled;
            });
        });
    });
});
</script>
<?php require '../../layout/footer.php';?>
