<?php
$q=trim((string)($_GET['historico']??''));$situacao=$_GET['situacao']??'todos';$ini=$_GET['data_ini']??'';$fim=$_GET['data_fim']??'';
$lista=array_values(array_filter($itens,function($i)use($q,$ini,$fim,$situacao){return $i['status']!=='ESTORNADO'&&(!$q||stripos($i['descricao'],$q)!==false)&&(!$ini||$i['data_compra']>=$ini)&&(!$fim||$i['data_compra']<=$fim)&&($situacao==='todos'||($situacao==='conciliados'?!empty($i['cpcontador']):empty($i['cpcontador'])));}));
$itensPorId=array_column($itens,null,'id');
$s=$pdo_master->prepare("SELECT debito_id,credito_id,valor FROM financeiro_cc_estornos WHERE fatura_id=? AND empresa_id=? ORDER BY debito_id");$s->execute([$faturaId,$empresa]);$estornos=$s->fetchAll(PDO::FETCH_ASSOC);
$totalEstornado=array_sum(array_column($estornos,'valor'));
$debitosEstornaveis=array_values(array_filter($itens,static function($i){return $i['natureza']==='D' && $i['status']!=='ESTORNADO' && !$i['cpcontador'];}));
$creditosEstornaveis=array_values(array_filter($itens,static function($i){return $i['natureza']==='C' && $i['status']!=='ESTORNADO' && !$i['cpcontador'];}));
$vinculados=array_values(array_filter($lista,static function($i){return $i['natureza']==='D'&&!empty($i['cpcontador']);}));
$sqlCp="SELECT cp.CPCONTADOR,cp.DTCOMPRA,cp.DTVENC,cp.TITULO,COALESCE(NULLIF(cp.VLRRESTANTE,0),cp.VLRPARCELA,cp.VALORCOMPRA) valor,COALESCE(NULLIF(f.APELIDO,''),f.NOME) fornecedor FROM armazem_cp001 cp LEFT JOIN armazem_cp003 f ON f.EMPRESA=cp.EMPRESA AND f.FCONTADOR=cp.FCONTADOR WHERE cp.EMPRESA=? AND cp.STATUS<>'QT' AND cp.DTPAGTO IS NULL AND COALESCE(cp.VLRPAGO,0)=0 AND COALESCE(cp.excluido_firebird,'N')<>'S' AND NOT EXISTS(SELECT 1 FROM financeiro_cc_itens x WHERE x.empresa_id=cp.EMPRESA AND x.cpcontador=cp.CPCONTADOR)";$parCp=[$empresa];if($ini){$sqlCp.=" AND DATE(cp.DTCOMPRA)>=?";$parCp[]=$ini;}if($fim){$sqlCp.=" AND DATE(cp.DTCOMPRA)<=?";$parCp[]=$fim;}if($q){$sqlCp.=" AND (cp.TITULO LIKE ? OR f.NOME LIKE ? OR f.APELIDO LIKE ?)";$busca='%'.$q.'%';array_push($parCp,$busca,$busca,$busca);}$sqlCp.=" ORDER BY cp.DTCOMPRA DESC,cp.CPCONTADOR DESC";$stmtCp=$pdo_master->prepare($sqlCp);$stmtCp->execute($parCp);$cpSistema=$stmtCp->fetchAll(PDO::FETCH_ASSOC);
$seguros=[];$manual=[];$sem=[];$contagens=cccContarValoresPendentes($lista);
foreach($lista as $i){
    if($i['natureza']!=='D'||$i['cpcontador'])continue;
    $c=cccCandidatos($pdo_master,$i,$fatura['vencimento']);
    $automatico=cccCandidatoAutomatico($i,$c,$contagens,$fatura['vencimento']);
    if($automatico)$seguros[]=[$i,$automatico];
    elseif($c)$manual[]=[$i,$c];
    else $sem[]=$i;
}
function ccForm(int $fid,int $iid,int $cp):string{return '<form method="post"><input type="hidden" name="acao" value="vincular"><input type="hidden" name="fatura_id" value="'.$fid.'"><input type="hidden" name="item_id" value="'.$iid.'"><input type="hidden" name="cpcontador" value="'.$cp.'"><button class="btn btn-sm btn-primary">Conciliar</button></form>';}
function ccParcelaExtrato(array $item):string
{
    $tipo=(string)($item['tipo_lancamento']??'');
    return preg_match('/(\d+)\s*\/\s*(\d+)/',$tipo,$m)?$m[1].'/'.$m[2]:'-';
}
require '../../layout/header.php';?>
<style>
.fatura-cartao-quadro,.sistema-cp-quadro{overflow-x:visible}
.conciliacao-fontes>form{display:none}
.fatura-cartao-quadro table,.sistema-cp-quadro table{table-layout:fixed;width:100%;font-size:12px}
.fatura-cartao-quadro th,.fatura-cartao-quadro td,.sistema-cp-quadro th,.sistema-cp-quadro td{white-space:normal;overflow-wrap:break-word;vertical-align:middle}
.fatura-cartao-quadro th:nth-child(1),.fatura-cartao-quadro td:nth-child(1){width:40px;text-align:center}
.fatura-cartao-quadro th:nth-child(2),.fatura-cartao-quadro td:nth-child(2){width:78px}
.fatura-cartao-quadro th:nth-child(4),.fatura-cartao-quadro td:nth-child(4){width:56px;text-align:center;white-space:nowrap}
.fatura-cartao-quadro th:nth-child(5),.fatura-cartao-quadro td:nth-child(5){width:88px;white-space:nowrap}
.fatura-cartao-quadro th:nth-child(6),.fatura-cartao-quadro td:nth-child(6){width:82px}
.sistema-cp-quadro th:nth-child(1),.sistema-cp-quadro td:nth-child(1){width:38px}
.sistema-cp-quadro th:nth-child(2),.sistema-cp-quadro td:nth-child(2){width:30%}
.sistema-cp-quadro th:nth-child(3),.sistema-cp-quadro td:nth-child(3),.sistema-cp-quadro th:nth-child(4),.sistema-cp-quadro td:nth-child(4){width:60px}
.sistema-cp-quadro th:nth-child(5),.sistema-cp-quadro td:nth-child(5){width:auto}
.sistema-cp-quadro th:nth-child(6),.sistema-cp-quadro td:nth-child(6){width:72px;white-space:nowrap}
@media(max-width:768px){.fatura-cartao-quadro,.sistema-cp-quadro{overflow-x:auto}}
@media(min-width:992px){.conciliacao-fontes>.col-xl-7,.conciliacao-fontes>.col-xl-5{flex:0 0 auto;width:50%}}
</style>
<section class="card mb-3"><div class="card-body d-flex justify-content-between align-items-center"><div><span class="badge text-bg-primary mb-2">Financeiro</span><h1 class="h4 mb-1">Conciliacao de Cartao de Credito</h1><p class="text-muted mb-0">Compare a fatura com os lancamentos do sistema antes de conciliar.</p></div><a href="conciliacao_cartao_credito.php" class="btn btn-outline-secondary">Voltar</a></div></section>
<?php if($msg):?><div class="alert alert-success"><?=htmlspecialchars($msg)?></div><?php endif;?><?php if($erro):?><div class="alert alert-danger"><?=htmlspecialchars($erro)?></div><?php endif;?>
<section class="card mb-3"><div class="card-body"><form class="row g-2 align-items-end"><input type="hidden" name="fatura_id" value="<?=$faturaId?>"><div class="col-md-2"><label class="form-label">Data inicial</label><input type="date" name="data_ini" value="<?=htmlspecialchars($ini)?>" class="form-control"></div><div class="col-md-2"><label class="form-label">Data final</label><input type="date" name="data_fim" value="<?=htmlspecialchars($fim)?>" class="form-control"></div><div class="col-md-4"><label class="form-label">Historico</label><input name="historico" value="<?=htmlspecialchars($q)?>" placeholder="Buscar no historico" class="form-control"></div><div class="col-md-2"><label class="form-label">Situacao</label><select name="situacao" class="form-select"><option value="pendentes" <?=$situacao==='pendentes'?'selected':''?>>Nao conciliados</option><option value="conciliados" <?=$situacao==='conciliados'?'selected':''?>>Conciliados</option><option value="todos" <?=$situacao==='todos'?'selected':''?>>Todos</option></select></div><div class="col-md-2"><button class="btn btn-primary w-100">Filtrar</button></div></form></div></section>
<div class="row g-3 mb-3"><div class="col-md-4"><div class="border p-3"><small class="text-muted">Fatura filtrada</small><div class="h4"><?=moedaCartaoCredito(array_sum(array_map(function($i){return $i['natureza']==='D'?(float)$i['valor']:($i['natureza']==='C'?-(float)$i['valor']:0);},$lista)))?></div><small><?=count($lista)?> lancamento(s)</small></div></div><div class="col-md-4"><div class="border p-3"><small class="text-muted">Sistema CP001 filtrado</small><div class="h4"><?=moedaCartaoCredito(array_sum(array_column($cpSistema,'valor')))?></div><small><?=count($cpSistema)?> lancamento(s)</small></div></div><div class="col-md-4"><div class="border p-3"><small class="text-muted">Sugestoes automaticas seguras</small><div class="h4"><?=count($seguros)?></div><small><?=count($manual)?> para escolha manual</small></div></div></div>
<section class="card mb-3"><div class="card-header d-flex justify-content-between align-items-center"><h2 class="h6 mb-0">Baixa dos CPs da fatura</h2><span class="badge text-bg-light border"><?=htmlspecialchars($fatura['status'])?></span></div><div class="card-body">
<?php if($fatura['status']==='IMPORTADA'):?>
<div class="row g-2 mb-3"><div class="col-md-3">Compras a baixar: <strong><?=moedaCartaoCredito((float)$fatura['total_debitos']-$totalEstornado)?></strong></div><div class="col-md-3">Valor liquido da fatura: <strong><?=moedaCartaoCredito($fatura['total_fatura'])?></strong></div><div class="col-md-3">Credito sem par: <strong><?=moedaCartaoCredito((float)$fatura['total_creditos']-$totalEstornado)?></strong></div><div class="col-md-3">Compras sem CP: <strong><?=$pendentesFechamento?></strong></div></div>
<?php if($bloqueioPagamento):?><div class="alert alert-warning mb-3"><?=htmlspecialchars($bloqueioPagamento)?></div><?php endif;?>
<form method="post" class="row g-2 align-items-end" onsubmit="return confirm('Confirmar baixa de todos os CPs na conta 39? Os pagamentos bancarios nao serao lancados automaticamente.');"><input type="hidden" name="acao" value="baixar_cps_fatura"><input type="hidden" name="fatura_id" value="<?=$faturaId?>"><input type="hidden" name="token" value="<?=htmlspecialchars($_SESSION['cc_fechamento_token'])?>"><div class="col-md-4"><label class="form-label">Data da baixa dos CPs</label><input class="form-control" type="date" name="data_baixa" value="<?=date('Y-m-d')?>" required></div><div class="col-md-4"><button class="btn btn-primary w-100" <?=$pendentesFechamento||$bloqueioPagamento?'disabled':''?>>Baixar CPs na conta 39</button></div></form>
<?php elseif($fatura['status']==='ENCERRADA' && !$fechamento):?><div>Fatura fechada e lancada. Todos os CPs foram baixados na conta 39. Os pagamentos por debito bancario ou boleto devem ser conciliados nessa conta.</div>
<?php elseif($fatura['status']==='AJUSTE_PENDENTE' && $fechamento):?>
<p class="mb-3">Pagamento de <?=moedaCartaoCredito($fechamento['total_pagamento'])?> registrado. A devolucao de <?=moedaCartaoCredito($fechamento['total_ajuste'])?> ainda precisa ser creditada na conta 39.</p><form method="post" class="row g-2 align-items-end" onsubmit="return confirm('Registrar o credito da devolucao na conta 39?');"><input type="hidden" name="acao" value="ajustar_credito"><input type="hidden" name="fatura_id" value="<?=$faturaId?>"><input type="hidden" name="token" value="<?=htmlspecialchars($_SESSION['cc_fechamento_token'])?>"><div class="col-md-8"><label class="form-label">TIPOES do credito da devolucao</label><select name="tipoes_ajuste" class="form-select" required><option value="">Selecione</option><?php foreach($tiposAjuste as $tipo):?><option value="<?=(int)$tipo['ESCONTADOR']?>"><?=htmlspecialchars($tipo['DESCES'].' ('.$tipo['ESCONTADOR'].')')?></option><?php endforeach;?></select></div><div class="col-md-4"><button class="btn btn-primary w-100">Registrar ajuste e encerrar</button></div></form>
<?php elseif($fechamento):?><div>Fatura encerrada. Pagamento de <?=moedaCartaoCredito($fechamento['total_pagamento'])?> pela conta <?=(int)$fechamento['conta_pagamento']?> em <?=dataCartaoCredito($fechamento['data_pagamento'])?>.</div><?php endif;?>
</div></section>
<section class="card mb-3"><div class="card-header d-flex justify-content-between align-items-center"><h2 class="h6 mb-0">Itens estornados na fatura</h2><span class="badge text-bg-secondary"><?=count($estornos)?> par(es)</span></div>
<?php if($fatura['status']==='IMPORTADA' && $debitosEstornaveis && $creditosEstornaveis):?><div class="card-body border-bottom"><form method="post" class="row g-2 align-items-end"><input type="hidden" name="acao" value="marcar_estorno"><input type="hidden" name="fatura_id" value="<?=$faturaId?>"><div class="col-md-5"><label class="form-label">Debito estornado</label><select name="debito_id" class="form-select" required><option value="">Selecione</option><?php foreach($debitosEstornaveis as $i):?><option value="<?=(int)$i['id']?>">#<?=(int)$i['id']?> | <?=htmlspecialchars($i['descricao'])?> | <?=moedaCartaoCredito($i['valor'])?></option><?php endforeach;?></select></div><div class="col-md-5"><label class="form-label">Credito correspondente</label><select name="credito_id" class="form-select" required><option value="">Selecione</option><?php foreach($creditosEstornaveis as $i):?><option value="<?=(int)$i['id']?>">#<?=(int)$i['id']?> | <?=htmlspecialchars($i['descricao'])?> | <?=moedaCartaoCredito($i['valor'])?></option><?php endforeach;?></select></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Confirmar estorno</button></div></form></div><?php endif;?>
<div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead class="table-primary"><tr><th>Debito</th><th>Credito</th><th class="text-end">Valor de cada item</th><th class="text-end">Saldo</th></tr></thead><tbody><?php foreach($estornos as $par):$d=$itensPorId[$par['debito_id']]??null;$c=$itensPorId[$par['credito_id']]??null;?><tr><td>#<?=(int)$par['debito_id']?> | <?=htmlspecialchars($d['descricao']??'-')?></td><td>#<?=(int)$par['credito_id']?> | <?=htmlspecialchars($c['descricao']??'-')?></td><td class="text-end"><?=moedaCartaoCredito($par['valor'])?></td><td class="text-end">R$ 0,00</td></tr><?php endforeach;?><?php if(!$estornos):?><tr><td colspan="4" class="text-center text-muted py-3">Nenhum estorno confirmado nesta fatura.</td></tr><?php endif;?></tbody></table></div></section>
<?php if($vinculados):?><section class="card mb-3"><div class="card-header d-flex justify-content-between align-items-center"><h2 class="h6 mb-0">Itens conciliados com CP</h2><span class="badge text-bg-success"><?=count($vinculados)?></span></div><div class="table-responsive" style="max-height:400px"><table class="table table-sm table-hover align-middle mb-0"><thead class="table-primary"><tr><th>Fatura</th><th>Data</th><th>Historico</th><th>CP</th><th class="text-end">Valor</th></tr></thead><tbody><?php foreach($vinculados as $i):?><tr><td>#<?=(int)$i['id']?></td><td><?=dataCartaoCredito($i['data_compra'])?></td><td><?=htmlspecialchars($i['descricao'])?></td><td><?=(int)$i['cpcontador']?></td><td class="text-end"><?=moedaCartaoCredito($i['valor'])?></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>
<?php if($fatura['status']==='IMPORTADA'):?>
<?php function ccTabela(array $grupos,string $titulo,string $texto,int $fid,string $cor='primary'):void{$form='lote-'.md5($titulo);?><section class="card mb-3"><div class="card-header d-flex justify-content-between align-items-center"><div><h2 class="h6 mb-1"><?=$titulo?></h2><small class="text-muted"><?=$texto?></small></div><button form="<?=$form?>" class="btn btn-sm btn-<?=$cor?>" <?=$grupos?'':'disabled'?>>Conciliar <?=count($grupos)?> selecionado(s)</button></div><form method="post" id="<?=$form?>"><input type="hidden" name="acao" value="vincular_lote"><input type="hidden" name="fatura_id" value="<?=$fid?>"><?php foreach($grupos as $m):?><input type="hidden" name="matches[<?=$m[0]['id']?>]" value="<?=$m[1]['CPCONTADOR']?>"><?php endforeach;?></form><div class="table-responsive"><table class="table table-sm table-hover align-middle mb-0"><thead class="table-<?=$cor?>"><tr><th>Fatura</th><th>Data fatura</th><th>Historico fatura</th><th>Sistema</th><th>Vencimento</th><th class="text-end">Valor</th><th>Acao</th></tr></thead><tbody><?php foreach($grupos as $m):?><tr><td>#<?=$m[0]['id']?></td><td><?=dataCartaoCredito($m[0]['data_compra'])?></td><td><?=htmlspecialchars($m[0]['descricao'])?></td><td>CP <?=$m[1]['CPCONTADOR']?> | <?=htmlspecialchars($m[1]['fornecedor'].' | '.$m[1]['TITULO'])?></td><td><?=dataCartaoCredito($m[1]['DTVENC'])?></td><td class="text-end"><?=moedaCartaoCredito($m[0]['valor'])?></td><td><?=ccForm($fid,$m[0]['id'],$m[1]['CPCONTADOR'])?></td></tr><?php endforeach;?><?php if(!$grupos):?><tr><td colspan="7" class="text-center text-muted py-3">Nenhum match para os filtros atuais.</td></tr><?php endif;?></tbody></table></div></section><?php }?>
<?php ccTabela($seguros,'Matches seguros automaticos','Data, valor e historico identificam uma unica correspondencia.',$faturaId);?>
<section class="card mb-3">
    <div class="card-header d-flex justify-content-between align-items-center">
        <div><h2 class="h6 mb-1">Conferencia manual guiada</h2><small class="text-muted">Escolha o CP correto em cada linha e concilie varios de uma vez.</small></div>
        <button form="manual-lote" class="btn btn-sm btn-primary" <?=$manual?'':'disabled'?>>Conciliar selecionados</button>
    </div>
    <form method="post" id="manual-lote"><input type="hidden" name="acao" value="vincular_lote"><input type="hidden" name="fatura_id" value="<?=$faturaId?>"></form>
    <div class="table-responsive"><table class="table table-sm table-hover align-middle mb-0"><thead class="table-primary"><tr><th>Fatura</th><th>Data</th><th>Historico</th><th class="text-end">Valor</th><th style="min-width:360px">Escolher lancamento do sistema</th></tr></thead><tbody>
    <?php foreach($manual as $m):?><tr><td>#<?=$m[0]['id']?></td><td><?=dataCartaoCredito($m[0]['data_compra'])?></td><td><?=htmlspecialchars($m[0]['descricao'])?></td><td class="text-end"><?=moedaCartaoCredito($m[0]['valor'])?></td><td><select form="manual-lote" name="matches[<?=$m[0]['id']?>]" class="form-select form-select-sm cc-manual-match"><option value="">Nao conciliar agora</option><?php foreach($m[1] as $cp):?><option value="<?=$cp['CPCONTADOR']?>">CP <?=$cp['CPCONTADOR']?> | <?=dataCartaoCredito($cp['DTVENC'])?> | <?=htmlspecialchars($cp['fornecedor'].' | '.$cp['TITULO'])?></option><?php endforeach;?></select></td></tr><?php endforeach;?>
    <?php if(!$manual):?><tr><td colspan="5" class="text-center text-muted py-3">Nenhum match manual para os filtros atuais.</td></tr><?php endif;?></tbody></table></div>
</section>
<div class="row g-3 align-items-start conciliacao-fontes">
<div class="col-xl-7"><section class="card h-100"><div class="card-header d-flex flex-wrap justify-content-between gap-2"><div><h2 class="h6 mb-1">Extrato da fatura nao conciliado</h2><div class="text-muted small">Use os filtros para consultar pendentes, conciliados ou todos os lancamentos.</div><div class="mt-2 d-flex flex-wrap gap-2"><span class="badge text-bg-light border"><?=count($sem)?> lancamento(s)</span><span class="badge text-bg-primary">Total: <?=moedaCartaoCredito(array_sum(array_column($sem,'valor')))?></span></div></div><div class="d-flex flex-wrap align-items-end gap-2"><div><label class="form-label small mb-1" for="tipoes-gerar-cp">TIPOES dos CPs</label><select form="gerar" id="tipoes-gerar-cp" name="tipoes" class="form-select form-select-sm" required><option value="">Selecione</option><?php foreach($tiposCp as $tipo):?><option value="<?=(int)$tipo['ESCONTADOR']?>"><?=htmlspecialchars($tipo['DESCES'].' ('.$tipo['ESCONTADOR'].')')?></option><?php endforeach;?></select></div><button type="button" class="btn btn-sm btn-outline-secondary" onclick="document.querySelectorAll('.cc-sem').forEach(x=>x.checked=true)">Selecionar todos</button><button form="gerar" class="btn btn-sm btn-primary" <?=$tiposCp?'':'disabled'?>>Gerar CP selecionados</button></div></div><div class="table-responsive fatura-cartao-quadro"><table class="table table-sm table-hover align-middle mb-0"><thead class="table-primary"><tr><th>Sel.</th><th>Data</th><th>Historico</th><th>Parcela</th><th class="text-end">Valor</th><th>Status</th></tr></thead><tbody><?php foreach($sem as $i):?><tr><td><input form="gerar" class="cc-sem" type="checkbox" name="itens[]" value="<?=$i['id']?>"></td><td><?=dataCartaoCredito($i['data_compra'])?></td><td><?=htmlspecialchars($i['descricao'])?></td><td><?=htmlspecialchars(ccParcelaExtrato($i))?></td><td class="text-end"><?=moedaCartaoCredito($i['valor'])?></td><td><span class="badge text-bg-warning">Pendente</span></td></tr><?php endforeach;?><?php if(!$sem):?><tr><td colspan="6" class="text-center text-muted py-3">Nenhum item pendente na fatura.</td></tr><?php endif;?></tbody></table></div></section></div><form method="post" id="gerar"><input type="hidden" name="acao" value="gerar"><input type="hidden" name="fatura_id" value="<?=$faturaId?>"></form>
<div class="col-xl-5"><section class="card h-100"><div class="card-header"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2"><h2 class="h6 mb-0">Sistema CP001 nao conciliado</h2><div class="d-flex flex-wrap gap-2"><span class="badge text-bg-light border"><?=count($cpSistema)?> lancamento(s)</span><span class="badge text-bg-primary">Total: <?=moedaCartaoCredito(array_sum(array_column($cpSistema,'valor')))?></span></div></div></div><div class="table-responsive sistema-cp-quadro"><table class="table table-sm table-hover align-middle mb-0"><thead class="table-primary"><tr><th>CP</th><th>Fornecedor</th><th>Compra</th><th>Vencimento</th><th>Historico</th><th class="text-end">Valor</th></tr></thead><tbody><?php foreach($cpSistema as $cp):?><tr><td><?=$cp['CPCONTADOR']?></td><td><?=htmlspecialchars($cp['fornecedor']?:'-')?></td><td><?=dataCartaoCredito($cp['DTCOMPRA'])?></td><td><?=dataCartaoCredito($cp['DTVENC'])?></td><td><?=htmlspecialchars($cp['TITULO']?:'-')?></td><td class="text-end"><?=moedaCartaoCredito($cp['valor'])?></td></tr><?php endforeach;?><?php if(!$cpSistema):?><tr><td colspan="6" class="text-center text-muted py-3">Nenhum CP do sistema para os filtros atuais.</td></tr><?php endif;?></tbody></table></div></section></div>
</div>
<?php else:?>
<section class="card mb-3"><div class="card-header fw-semibold">Lancamentos da fatura</div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead class="table-primary"><tr><th>Data</th><th>Historico</th><th>Natureza</th><th>Situacao</th><th>CP</th><th class="text-end">Valor</th></tr></thead><tbody><?php foreach($itens as $i):?><tr><td><?=dataCartaoCredito($i['data_compra'])?></td><td><?=htmlspecialchars($i['descricao'])?></td><td><?=htmlspecialchars($i['natureza'])?></td><td><?=htmlspecialchars($i['status'])?></td><td><?=$i['cpcontador']?(int)$i['cpcontador']:'-'?></td><td class="text-end"><?=moedaCartaoCredito($i['valor'])?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php endif;?>
<script>
document.querySelectorAll('.cc-manual-match').forEach(select => {
    select.addEventListener('change', () => {
        const escolhidos = new Set([...document.querySelectorAll('.cc-manual-match')].map(item => item.value).filter(Boolean));
        document.querySelectorAll('.cc-manual-match').forEach(item => {
            [...item.options].forEach(option => {
                option.disabled = option.value !== '' && option.value !== item.value && escolhidos.has(option.value);
                option.hidden = option.disabled;
            });
        });
    });
});
</script>
<?php require '../../layout/footer.php';?>
