<?php
require '../../config/auth.php';require '../../config/conexao.php';require_once '../../config/modulos.php';require_once __DIR__.'/_conciliacao_cartao_lib.php';require_once __DIR__.'/_conciliacao_cartao_fechamento.php';
$empresa=(int)($_SESSION['empresa_id']??0);$usuario=(int)($_SESSION['usuario_id']??0);if(strtoupper((string)($_SESSION['nivel']??''))!=='MASTER'){renderizarAcessoNegadoModulo();exit;}cccGarantirTabelas($pdo_master);cccGarantirFechamentos($pdo_master);$erro='';$msg='';$faturaId=(int)($_REQUEST['fatura_id']??0);
if(empty($_SESSION['cc_fechamento_token']))$_SESSION['cc_fechamento_token']=bin2hex(random_bytes(32));
function cccUrl(int $id=0,string $ok=''):string{return 'conciliacao_cartao_credito.php'.($id||$ok?'?'.http_build_query(array_filter(['fatura_id'=>$id,'ok'=>$ok])):'');}
try{if($_SERVER['REQUEST_METHOD']==='POST'){$a=$_POST['acao']??'';
if(in_array($a,['baixar_cps_fatura','ajustar_credito'],true) && !hash_equals($_SESSION['cc_fechamento_token'],(string)($_POST['token']??'')))throw new RuntimeException('Sessao expirada. Atualize a pagina antes de continuar.');
if($a==='baixar_cps_fatura'){cccBaixarCpsFatura($pdo_master,$empresa,$faturaId,$usuario,trim((string)($_POST['data_baixa']??'')));header('Location: '.cccUrl($faturaId,'cps_baixados'));exit;}
if($a==='ajustar_credito'){cccAjustarCreditoFatura($pdo_master,$empresa,$faturaId,$usuario,(int)($_POST['tipoes_ajuste']??0));header('Location: '.cccUrl($faturaId,'encerrada'));exit;}
if($a==='salvar_cartao'){$id=(int)($_POST['cartao_id']??0);$nome=trim($_POST['nome']??'');$forn=(int)($_POST['fornecedor']??0);$dia=(int)($_POST['dia']??0);if(!$nome||$dia<1||$dia>31||!fornecedorCartaoExiste($pdo_master,$empresa,$forn))throw new RuntimeException('Preencha corretamente o cartao.');if($id){$s=$pdo_master->prepare("UPDATE financeiro_cc_cartoes SET nome=?,nome_norm=?,fornecedor_fcontador=?,dia_vencimento=? WHERE id=? AND empresa_id=?");$s->execute([$nome,normalizarDescricaoCartao($nome),$forn,$dia,$id,$empresa]);}else{$pdo_master->prepare("INSERT INTO financeiro_cc_cartoes(empresa_id,nome,nome_norm,fornecedor_fcontador,dia_vencimento,usuario_id)VALUES(?,?,?,?,?,?)")->execute([$empresa,$nome,normalizarDescricaoCartao($nome),$forn,$dia,$usuario?:null]);}header('Location: '.cccUrl(0,'cartao'));exit;}
if($a==='alternar'){$pdo_master->prepare("UPDATE financeiro_cc_cartoes SET ativo=IF(ativo='S','N','S') WHERE id=? AND empresa_id=?")->execute([(int)$_POST['cartao_id'],$empresa]);header('Location: '.cccUrl());exit;}
if($a==='importar'){$cartao=(int)($_POST['cartao_id']??0);$comp=trim($_POST['competencia']??'');$upload=$_FILES['arquivo']??$_FILES['csv']??[];if(!preg_match('/^\d{4}-\d{2}$/',$comp)||empty($upload['tmp_name']))throw new RuntimeException('Informe cartao, competencia e arquivo da fatura.');$ext=strtolower(pathinfo((string)($upload['name']??''),PATHINFO_EXTENSION));if(!in_array($ext,['csv','pdf'],true))throw new RuntimeException('Envie uma fatura CSV ou PDF Mercado Pago.');$s=$pdo_master->prepare("SELECT * FROM financeiro_cc_cartoes WHERE id=? AND empresa_id=? AND ativo='S'");$s->execute([$cartao,$empresa]);$c=$s->fetch(PDO::FETCH_ASSOC);if(!$c)throw new RuntimeException('Cartao invalido.');$v=cccVencimento($comp,(int)$c['dia_vencimento']);$hash=hash_file('sha256',$upload['tmp_name']);if($ext==='pdf'){$resultado=lerPdfMercadoPagoPayload((string)($_POST['pdf_payload']??''),$upload['tmp_name'],$comp,$v);$linhas=$resultado['linhas'];$d=$resultado['debitos'];$cr=$resultado['creditos'];$total=$resultado['total'];}else{$linhas=lerCsvConciliacaoCartao($upload['tmp_name']);$d=$cr=0;foreach($linhas as $l){if($l['natureza']==='D')$d+=$l['valor'];elseif($l['natureza']==='C')$cr+=$l['valor'];}$total=$d-$cr;}$pdo_master->beginTransaction();$pdo_master->prepare("INSERT INTO financeiro_cc_faturas(empresa_id,cartao_id,competencia,vencimento,nome_arquivo,hash_arquivo,total_debitos,total_creditos,total_fatura,usuario_id)VALUES(?,?,?,?,?,?,?,?,?,?)")->execute([$empresa,$cartao,$comp,$v,$upload['name'],$hash,$d,$cr,$total,$usuario?:null]);$fid=(int)$pdo_master->lastInsertId();$ins=$pdo_master->prepare("INSERT INTO financeiro_cc_itens(fatura_id,empresa_id,data_compra,descricao,categoria,tipo_lancamento,valor,natureza,hash_item,status)VALUES(?,?,?,?,?,?,?,?,?,?)");$oc=[];foreach($linhas as $l){$b=implode('|',[$l['data_compra'],$l['descricao'],$l['categoria'],$l['tipo_lancamento'],$l['valor'],$l['natureza']]);$oc[$b]=($oc[$b]??0)+1;$ins->execute([$fid,$empresa,$l['data_compra'],$l['descricao'],$l['categoria'],$l['tipo_lancamento'],$l['valor'],$l['natureza'],hash('sha256',$b.'|'.$oc[$b]),$l['natureza']==='D'?'PENDENTE':'INFORMATIVO']);}$pdo_master->commit();header('Location: '.cccUrl($fid,'importada'));exit;}
if($a==='match_auto'){$s=$pdo_master->prepare("SELECT i.*,f.vencimento FROM financeiro_cc_itens i JOIN financeiro_cc_faturas f ON f.id=i.fatura_id WHERE i.fatura_id=? AND i.empresa_id=? AND i.natureza='D' AND i.status<>'ESTORNADO' AND i.cpcontador IS NULL");$s->execute([$faturaId,$empresa]);$pendentes=$s->fetchAll(PDO::FETCH_ASSOC);$contagens=cccContarValoresPendentes($pendentes);$n=0;foreach($pendentes as $i){$c=cccCandidatoAutomatico($i,cccCandidatos($pdo_master,$i,$i['vencimento']),$contagens,$i['vencimento']);if($c){cccVincular($pdo_master,$empresa,(int)$i['id'],(int)$c['CPCONTADOR'],$usuario);$n++;}}header('Location: '.cccUrl($faturaId,'auto').'&qtd='.$n);exit;}
if($a==='vincular_lote'){$matches=$_POST['matches']??[];if(!is_array($matches))$matches=[];$selecionados=array_values(array_filter(array_map('intval',$matches),static function($cp){return $cp>0;}));if(count($selecionados)!==count(array_unique($selecionados)))throw new RuntimeException('Cada CP pode ser escolhido para apenas um item da fatura.');$n=0;$pdo_master->beginTransaction();foreach($matches as $itemId=>$cp){$itemId=(int)$itemId;$cp=(int)$cp;if($itemId>0&&$cp>0){cccVincular($pdo_master,$empresa,$itemId,$cp,$usuario);$n++;}}$pdo_master->commit();header('Location: '.cccUrl($faturaId,'lote').'&qtd='.$n);exit;}
if($a==='vincular'){cccVincular($pdo_master,$empresa,(int)$_POST['item_id'],(int)$_POST['cpcontador'],$usuario);header('Location: '.cccUrl($faturaId,'vinculado'));exit;}
if($a==='marcar_estorno'){
    $debitoId=(int)($_POST['debito_id']??0);$creditoId=(int)($_POST['credito_id']??0);
    if($debitoId<=0 || $creditoId<=0 || $debitoId===$creditoId)throw new RuntimeException('Selecione um debito e um credito distintos.');
    $pdo_master->beginTransaction();
    $s=$pdo_master->prepare("SELECT status FROM financeiro_cc_faturas WHERE id=? AND empresa_id=? FOR UPDATE");$s->execute([$faturaId,$empresa]);
    if($s->fetchColumn()!=='IMPORTADA')throw new RuntimeException('Somente faturas ainda nao pagas aceitam estornos.');
    $s=$pdo_master->prepare("SELECT id,natureza,valor,cpcontador,status FROM financeiro_cc_itens WHERE fatura_id=? AND empresa_id=? AND id IN (?,?) ORDER BY id FOR UPDATE");
    $s->execute([$faturaId,$empresa,$debitoId,$creditoId]);$par=[];foreach($s as $item)$par[(int)$item['id']]=$item;
    if(count($par)!==2 || ($par[$debitoId]['natureza']??'')!=='D' || ($par[$creditoId]['natureza']??'')!=='C' || $par[$debitoId]['cpcontador'] || $par[$creditoId]['cpcontador'] || $par[$debitoId]['status']==='ESTORNADO' || $par[$creditoId]['status']==='ESTORNADO' || (int)round((float)$par[$debitoId]['valor']*100)!==(int)round((float)$par[$creditoId]['valor']*100))throw new RuntimeException('Estorno exige debito e credito livres, da mesma fatura e de valor igual.');
    $pdo_master->prepare("INSERT INTO financeiro_cc_estornos(fatura_id,empresa_id,debito_id,credito_id,valor,usuario_id) VALUES(?,?,?,?,?,?)")->execute([$faturaId,$empresa,$debitoId,$creditoId,$par[$debitoId]['valor'],$usuario?:null]);
    $s=$pdo_master->prepare("UPDATE financeiro_cc_itens SET status='ESTORNADO',usuario_id=? WHERE id IN (?,?) AND fatura_id=? AND empresa_id=?");$s->execute([$usuario?:null,$debitoId,$creditoId,$faturaId,$empresa]);
    if($s->rowCount()!==2)throw new RuntimeException('Nao foi possivel marcar os dois itens.');
    $pdo_master->commit();header('Location: '.cccUrl($faturaId,'estorno'));exit;
}
if($a==='gerar'){
    $ids=array_values(array_unique(array_filter(array_map('intval',(array)($_POST['itens']??[])),static function($id){return $id>0;})));
    $tipoes=(int)($_POST['tipoes']??0);
    if(!$ids)throw new RuntimeException('Selecione os itens sem match.');
    if($tipoes<=0)throw new RuntimeException('Selecione o TIPOES dos CPs.');
    $s=$pdo_master->prepare("SELECT ESCONTADOR FROM armazem_bnc005 WHERE EMPRESA=? AND ESCONTADOR=? AND TIPOMOV='D' AND COALESCE(REGDISAB,'N')<>'S' AND COALESCE(excluido_firebird,'N')<>'S'");
    $s->execute([$empresa,$tipoes]);if(!$s->fetchColumn())throw new RuntimeException('TIPOES invalido para a empresa.');
    $s=$pdo_master->prepare("SELECT f.*,c.nome cartao_nome,c.fornecedor_fcontador FROM financeiro_cc_faturas f JOIN financeiro_cc_cartoes c ON c.id=f.cartao_id WHERE f.id=? AND f.empresa_id=?");
    $s->execute([$faturaId,$empresa]);$f=$s->fetch(PDO::FETCH_ASSOC);
    if(!$f)throw new RuntimeException('Fatura nao encontrada.');
    if($f['status']!=='IMPORTADA')throw new RuntimeException('A fatura ja teve o pagamento iniciado. Nao e possivel gerar novos CPs.');
    $s=$pdo_master->prepare("SELECT NOME,APELIDO FROM armazem_cp003 WHERE EMPRESA=? AND FCONTADOR=? AND COALESCE(excluido_firebird,'N')<>'S'");
    $s->execute([$empresa,(int)$f['fornecedor_fcontador']]);
    $fornecedorCartao=$s->fetch(PDO::FETCH_ASSOC);
    if(!$fornecedorCartao)throw new RuntimeException('Fornecedor do cartao nao encontrado.');
    $nomeFornecedor=normalizarDescricaoCartao((string)$fornecedorCartao['NOME']);
    $apelidoFornecedor=normalizarDescricaoCartao((string)$fornecedorCartao['APELIDO']);
    if($nomeFornecedor!=='CARTAO DE CREDITO'&&$apelidoFornecedor!=='CARTAO DE CREDITO')throw new RuntimeException('O fornecedor configurado no cartao deve ser CARTAO DE CREDITO. Nenhum CP foi gerado.');
    $pdo_master->beginTransaction();
    $marcadores=implode(',',array_fill(0,count($ids),'?'));
    $s=$pdo_master->prepare("SELECT * FROM financeiro_cc_itens WHERE fatura_id=? AND empresa_id=? AND natureza='D' AND status<>'ESTORNADO' AND cpcontador IS NULL AND id IN ($marcadores) ORDER BY id FOR UPDATE");
    $s->execute(array_merge([$faturaId,$empresa],$ids));$selecionados=$s->fetchAll(PDO::FETCH_ASSOC);
    if(count($selecionados)!==count($ids))throw new RuntimeException('Um dos itens ja foi conciliado ou nao pertence a esta fatura. Nenhum CP foi gerado.');
    foreach($selecionados as $i){
        if(cccCandidatos($pdo_master,$i,$f['vencimento']))throw new RuntimeException('O item #'.$i['id'].' possui CP candidato. Concilie-o antes de gerar novos titulos. Nenhum CP foi gerado.');
    }
    $atualizar=$pdo_master->prepare("UPDATE financeiro_cc_itens SET cpcontador=?,status='GERADO',usuario_id=?,conciliado_em=NOW() WHERE id=? AND cpcontador IS NULL");
    foreach($selecionados as $i){
        $cp=cccGerarCp($pdo_master,$i,$f,$usuario,$tipoes);
        $atualizar->execute([$cp,$usuario?:null,(int)$i['id']]);
        if($atualizar->rowCount()!==1)throw new RuntimeException('Nao foi possivel vincular o item #'.$i['id'].'. Nenhum CP foi gerado.');
    }
    $pdo_master->commit();
    header('Location: '.cccUrl($faturaId,'gerados').'&qtd='.count($selecionados));exit;
}
}}catch(Throwable $e){if($pdo_master->inTransaction())$pdo_master->rollBack();$erro=$e->getMessage();}
$ok=$_GET['ok']??'';$msg=['cartao'=>'Cartao salvo.','importada'=>'Fatura importada sem gerar financeiro.','vinculado'=>'CP conciliado.','paga'=>'Pagamento registrado. Ajuste de devolucao pendente, quando aplicavel.','encerrada'=>'Ajuste registrado e fatura encerrada.'][$ok]??($ok==='auto'?'Matches automaticos: '.(int)($_GET['qtd']??0):($ok==='gerados'?'CPs gerados: '.(int)($_GET['qtd']??0):''));$fornecedores=buscarFornecedoresCartaoCredito($pdo_master,$empresa);$s=$pdo_master->prepare("SELECT c.*,COALESCE(NULLIF(f.APELIDO,''),f.NOME) fornecedor FROM financeiro_cc_cartoes c JOIN armazem_cp003 f ON f.EMPRESA=c.empresa_id AND f.FCONTADOR=c.fornecedor_fcontador WHERE c.empresa_id=? ORDER BY c.nome");$s->execute([$empresa]);$cartoes=$s->fetchAll(PDO::FETCH_ASSOC);$editar=null;foreach($cartoes as $c)if((int)$c['id']===(int)($_GET['editar']??0))$editar=$c;$ativos=array_filter($cartoes,function($c){return $c['ativo']==='S';});$s=$pdo_master->prepare("SELECT f.*,c.nome cartao_nome FROM financeiro_cc_faturas f JOIN financeiro_cc_cartoes c ON c.id=f.cartao_id WHERE f.empresa_id=? ORDER BY f.vencimento DESC");$s->execute([$empresa]);$faturas=$s->fetchAll(PDO::FETCH_ASSOC);$fatura=null;$itens=[];if($faturaId){$s=$pdo_master->prepare("SELECT f.*,c.nome cartao_nome,c.fornecedor_fcontador,c.fornecedor_fcontador FROM financeiro_cc_faturas f JOIN financeiro_cc_cartoes c ON c.id=f.cartao_id WHERE f.id=? AND f.empresa_id=?");$s->execute([$faturaId,$empresa]);$fatura=$s->fetch(PDO::FETCH_ASSOC);$s=$pdo_master->prepare("SELECT * FROM financeiro_cc_itens WHERE fatura_id=? ORDER BY data_compra,id");$s->execute([$faturaId]);$itens=$s->fetchAll(PDO::FETCH_ASSOC);}
if($ok==='cps_baixados')$msg='Fatura fechada e CPs lancados na conta 39. Concilie os pagamentos diretamente nessa conta.';
if($ok==='estorno')$msg='Estorno registrado na fatura.';
if($fatura){
    $s=$pdo_master->prepare("SELECT ESCONTADOR,DESCES FROM armazem_bnc005 WHERE EMPRESA=? AND TIPOMOV='D' AND COALESCE(REGDISAB,'N')<>'S' AND COALESCE(excluido_firebird,'N')<>'S' ORDER BY DESCES,ESCONTADOR");$s->execute([$empresa]);$tiposCp=$s->fetchAll(PDO::FETCH_ASSOC);
    $s=$pdo_master->prepare("SELECT ESCONTADOR,DESCES FROM armazem_bnc005 WHERE EMPRESA=? AND TIPOMOV='C' AND COALESCE(CONTRAP_TIPOES,0)=0 AND COALESCE(REGDISAB,'N')<>'S' AND COALESCE(excluido_firebird,'N')<>'S' ORDER BY DESCES");$s->execute([$empresa]);$tiposAjuste=$s->fetchAll(PDO::FETCH_ASSOC);
    $s=$pdo_master->prepare("SELECT * FROM financeiro_cc_fechamentos WHERE fatura_id=? AND empresa_id=?");$s->execute([$faturaId,$empresa]);$fechamento=$s->fetch(PDO::FETCH_ASSOC)?:null;
    $pendentesFechamento=count(array_filter($itens,static function($i){return $i['natureza']==='D' && $i['status']!=='ESTORNADO' && !$i['cpcontador'];}));
    $bloqueioPagamento='';
    if($fatura['status']==='IMPORTADA'){
        try{
            if(!cccContaCartao($pdo_master,$empresa))throw new RuntimeException('A conta 39 de cartoes nao esta ativa para esta empresa.');
        }catch(RuntimeException $e){$bloqueioPagamento=$e->getMessage();}
    }
    require __DIR__.'/_conciliacao_cartao_view.php';exit;
}
require '../../layout/header.php';?>
<section class="card mb-4"><div class="card-body d-flex justify-content-between"><div><h1 class="h4 mb-1">Conciliacao de Cartao de Credito</h1><span class="text-muted">Concilie a fatura com CPs existentes antes de gerar pendencias.</span></div><a class="btn btn-outline-secondary" href="menu_financeiro.php">Voltar</a></div></section><?php if($msg):?><div class="alert alert-success"><?=htmlspecialchars($msg)?></div><?php endif;?><?php if($erro):?><div class="alert alert-danger"><?=htmlspecialchars($erro)?></div><?php endif;?>
<?php if(!$fatura):?><div class="row g-3 mb-4"><div class="col-lg-5"><section class="card h-100"><div class="card-header fw-semibold">Cadastro de cartao</div><div class="card-body"><form method="post" class="row g-2"><input type="hidden" name="acao" value="salvar_cartao"><input type="hidden" name="cartao_id" value="<?=(int)($editar['id']??0)?>"><div class="col-8"><label class="form-label">Cartao</label><input class="form-control" name="nome" value="<?=htmlspecialchars($editar['nome']??'')?>" required></div><div class="col-4"><label class="form-label">Vence dia</label><input class="form-control" type="number" min="1" max="31" name="dia" value="<?=htmlspecialchars((string)($editar['dia_vencimento']??''))?>" required></div><div class="col-12"><label class="form-label">Fornecedor</label><select class="form-select" name="fornecedor" required><option value="">Selecione...</option><?php foreach($fornecedores as $x):?><option value="<?=$x['FCONTADOR']?>" <?=(int)($editar['fornecedor_fcontador']??0)===(int)$x['FCONTADOR']?'selected':''?>><?=htmlspecialchars($x['nome'])?></option><?php endforeach;?></select></div><div><button class="btn btn-primary">Salvar</button></div></form></div></section></div><div class="col-lg-7"><section class="card h-100"><div class="card-header fw-semibold">Importar fatura</div><div class="card-body"><form method="post" enctype="multipart/form-data" class="row g-2" id="form-importar-fatura"><input type="hidden" name="acao" value="importar"><input type="hidden" name="pdf_payload" id="pdf-payload"><div class="col-md-7"><label class="form-label">Cartao</label><select class="form-select" name="cartao_id" required><option value="">Selecione...</option><?php foreach($ativos as $c):?><option value="<?=$c['id']?>"><?=htmlspecialchars($c['nome'].' | vence dia '.$c['dia_vencimento'])?></option><?php endforeach;?></select></div><div class="col-md-5"><label class="form-label">Competencia</label><input type="month" class="form-control" name="competencia" id="competencia-fatura" required></div><div class="col-12"><label class="form-label">Arquivo CSV ou PDF Mercado Pago</label><input type="file" class="form-control" name="arquivo" id="arquivo-fatura" accept=".csv,.pdf" required></div><div class="col-md-6 d-none" id="senha-pdf-wrap"><label class="form-label">Senha do PDF</label><input type="password" class="form-control" id="senha-pdf" autocomplete="off"></div><div class="col-12"><div class="form-text" id="pdf-status">CSV no formato habitual ou fatura PDF Mercado Pago.</div></div><div><button class="btn btn-success" id="btn-importar-fatura">Importar</button></div></form></div></section></div></div>
<section class="card mb-4"><div class="card-header fw-semibold">Cartoes cadastrados</div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Cartao</th><th>Fornecedor</th><th>Vencimento</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($cartoes as $c):?><tr><td><?=$c['nome']?></td><td><?=$c['fornecedor']?></td><td>Dia <?=$c['dia_vencimento']?></td><td><?=$c['ativo']==='S'?'Ativo':'Inativo'?></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="?editar=<?=$c['id']?>">Editar</a> <form class="d-inline" method="post"><input type="hidden" name="acao" value="alternar"><input type="hidden" name="cartao_id" value="<?=$c['id']?>"><button class="btn btn-sm btn-outline-secondary"><?=$c['ativo']==='S'?'Desativar':'Ativar'?></button></form></td></tr><?php endforeach;?></tbody></table></div></section>
<?php $emAndamento=array_values(array_filter($faturas,static function($f){return $f['status']!=='ENCERRADA';}));$encerradas=array_values(array_filter($faturas,static function($f){return $f['status']==='ENCERRADA';}));?>
<section class="card mb-3"><div class="card-header fw-semibold">Faturas em andamento</div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Cartao</th><th>Competencia</th><th>Vencimento</th><th class="text-end">Total</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($emAndamento as $f):?><tr><td><?=htmlspecialchars($f['cartao_nome'])?></td><td><?=htmlspecialchars($f['competencia'])?></td><td><?=dataCartaoCredito($f['vencimento'])?></td><td class="text-end"><?=moedaCartaoCredito($f['total_fatura'])?></td><td><?=htmlspecialchars($f['status']==='IMPORTADA'?'Em conciliacao':'Ajuste pendente')?></td><td class="text-end"><a class="btn btn-sm btn-primary" href="?fatura_id=<?=(int)$f['id']?>"><?=$f['status']==='IMPORTADA'?'Conciliar':'Abrir ajuste'?></a></td></tr><?php endforeach;?><?php if(!$emAndamento):?><tr><td colspan="6" class="text-center text-muted py-3">Nenhuma fatura em andamento.</td></tr><?php endif;?></tbody></table></div></section>
<section class="card"><div class="card-header fw-semibold">Historico de faturas</div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Cartao</th><th>Competencia</th><th>Vencimento</th><th class="text-end">Total</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($encerradas as $f):?><tr><td><?=htmlspecialchars($f['cartao_nome'])?></td><td><?=htmlspecialchars($f['competencia'])?></td><td><?=dataCartaoCredito($f['vencimento'])?></td><td class="text-end"><?=moedaCartaoCredito($f['total_fatura'])?></td><td>Fechada e lancada</td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="?fatura_id=<?=(int)$f['id']?>">Visualizar</a></td></tr><?php endforeach;?><?php if(!$encerradas):?><tr><td colspan="6" class="text-center text-muted py-3">Nenhuma fatura encerrada.</td></tr><?php endif;?></tbody></table></div></section>
<?php else:?><section class="card mb-3"><div class="card-header d-flex justify-content-between"><strong><?=$fatura['cartao_nome']?> | <?=$fatura['competencia']?> | Venc. <?=dataCartaoCredito($fatura['vencimento'])?></strong><a href="conciliacao_cartao_credito.php" class="btn btn-sm btn-outline-secondary">Faturas</a></div><div class="card-body d-flex gap-4"><span>Compras: <strong><?=moedaCartaoCredito($fatura['total_debitos'])?></strong></span><span>Creditos: <strong><?=moedaCartaoCredito($fatura['total_creditos'])?></strong></span><span>Total: <strong><?=moedaCartaoCredito($fatura['total_fatura'])?></strong></span></div></section>
<form method="post"><input type="hidden" name="acao" value="gerar"><input type="hidden" name="fatura_id" value="<?=$faturaId?>"><section class="card"><div class="card-header d-flex justify-content-between"><div><strong>Conciliacao com CP</strong><div class="small text-muted">Fatura e sugestoes de Contas a Pagar.</div></div><div><button form="auto" class="btn btn-outline-primary">Match automatico</button> <button class="btn btn-success">Gerar CP dos selecionados</button></div></div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th><input type="checkbox" onclick="document.querySelectorAll('.sem-match').forEach(x=>x.checked=this.checked)"></th><th>Fatura</th><th class="text-end">Valor</th><th>Conta a pagar / situacao</th></tr></thead><tbody><?php foreach($itens as $i):$c=$i['natureza']==='D'&&!$i['cpcontador']?cccCandidatos($pdo_master,$i,$fatura['vencimento']):[];?><tr><td><?php if($i['natureza']==='D'&&!$i['cpcontador']&&!$c):?><input class="sem-match" type="checkbox" name="itens[]" value="<?=$i['id']?>"><?php endif;?></td><td><?=dataCartaoCredito($i['data_compra'])?> | <strong><?=htmlspecialchars($i['descricao'])?></strong></td><td class="text-end"><?=$i['natureza']==='D'?'':'-'?><?=moedaCartaoCredito($i['valor'])?></td><td><?php if($i['cpcontador']):?><span class="badge text-bg-success">CP <?=$i['cpcontador']?></span><?php elseif($i['natureza']!=='D'):?><span class="text-muted">Credito/informativo</span><?php elseif($c):?><form method="post" class="d-flex gap-2"><input type="hidden" name="acao" value="vincular"><input type="hidden" name="fatura_id" value="<?=$faturaId?>"><input type="hidden" name="item_id" value="<?=$i['id']?>"><select class="form-select form-select-sm" name="cpcontador" required><option value="">Sugestoes...</option><?php foreach($c as $x):?><option value="<?=$x['CPCONTADOR']?>">CP <?=$x['CPCONTADOR']?> | <?=$x['fornecedor']?> | <?=$x['TITULO']?></option><?php endforeach;?></select><button class="btn btn-sm btn-primary">Conciliar</button></form><?php else:?><span class="badge text-bg-warning">Sem match - gerar CP</span><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section></form><form method="post" id="auto"><input type="hidden" name="acao" value="match_auto"><input type="hidden" name="fatura_id" value="<?=$faturaId?>"></form><?php endif;?>
<script type="module" src="../../assets/js/conciliacao_cartao_pdf.js"></script>
<?php require '../../layout/footer.php';?>
