CREATE TABLE IF NOT EXISTS auxiliar_sync_tokens (
    source VARCHAR(16) NOT NULL PRIMARY KEY,
    token_sha256 CHAR(64) NOT NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
